import { User, AttendanceSummary, Task, TimetableEntry, Notice, AdminStats, StudentListItem } from '../types';

export const mockUsers: Record<string, { user: User; passwordPlain: string }> = {
  'admin@campus.edu': {
    user: {
      id: 'usr_admin_01',
      name: 'Dr. Rajesh Verma',
      email: 'admin@campus.edu',
      role: 'ADMIN',
    },
    passwordPlain: 'admin123',
  },
  'student@campus.edu': {
    user: {
      id: 'usr_student_01',
      name: 'Aarav Sharma',
      email: 'student@campus.edu',
      role: 'STUDENT',
      student: {
        id: 'std_01',
        userId: 'usr_student_01',
        enrollmentNumber: '21BCSE104',
        course: 'B.Tech Computer Science & Engineering',
        semester: 'Semester 6',
        department: 'School of Computing & Data Sciences',
      },
    },
    passwordPlain: 'student123',
  },
};

export const mockAttendanceRecords = [
  {
    id: 'att_01',
    subject: 'Data Structures & Algorithms',
    totalClasses: 42,
    attendedClasses: 38,
    percentage: 90.5,
  },
  {
    id: 'att_02',
    subject: 'Cloud Computing & DevOps',
    totalClasses: 34,
    attendedClasses: 28,
    percentage: 82.4,
  },
  {
    id: 'att_03',
    subject: 'Artificial Intelligence & Neural Nets',
    totalClasses: 40,
    attendedClasses: 32,
    percentage: 80.0,
  },
  {
    id: 'att_04',
    subject: 'Database Management Systems',
    totalClasses: 38,
    attendedClasses: 26,
    percentage: 68.4,
  },
  {
    id: 'att_05',
    subject: 'Software Engineering & Agile Methodologies',
    totalClasses: 30,
    attendedClasses: 27,
    percentage: 90.0,
  },
];

export const mockTasks: Task[] = [
  {
    id: 'tsk_01',
    title: 'Implement Red-Black Tree in C++',
    description: 'Complete insertion, rotation, and balance verification modules for DSA lab evaluation.',
    deadline: new Date(Date.now() + 86400000 * 2).toISOString(),
    status: 'IN_PROGRESS',
    priority: 'HIGH',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'tsk_02',
    title: 'Deploy Dockerized Microservice on Kubernetes',
    description: 'Configure Ingress controller, ConfigMaps, and Persistent Volume Claims on minikube.',
    deadline: new Date(Date.now() + 86400000 * 4).toISOString(),
    status: 'TODO',
    priority: 'HIGH',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'tsk_03',
    title: 'AI Lab: Convolutional Neural Network on CIFAR-10',
    description: 'Train PyTorch ResNet model achieving >85% accuracy on test set with confusion matrix.',
    deadline: new Date(Date.now() + 86400000 * 6).toISOString(),
    status: 'TODO',
    priority: 'MEDIUM',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'tsk_04',
    title: 'SQL Normalization & BCNF Proof Documentation',
    description: 'Deconstruct relational database tables up to Boyce-Codd Normal Form with functional dependency trees.',
    deadline: new Date(Date.now() - 86400000).toISOString(),
    status: 'COMPLETED',
    priority: 'LOW',
    createdAt: new Date().toISOString(),
  },
];

export const mockNotices: Notice[] = [
  {
    id: 'not_01',
    title: 'End-Semester Theory & Practical Examination Schedule (Spring 2026)',
    content: 'The Office of the Controller of Examinations has published the finalized timetable for Semester 6. Students with overall attendance below 75% must contact Academic Affairs by Friday.',
    category: 'Exams',
    authorName: 'Office of the Controller of Examinations',
    createdAt: new Date(Date.now() - 86400000 * 1).toISOString(),
  },
  {
    id: 'not_02',
    title: 'Smart India Hackathon 2026 - Internal College Selection Round',
    content: 'Team registrations for the internal smart campus innovation hackathon are now open. Top 5 teams will represent the university with full sponsorship and lab equipment access.',
    category: 'Events',
    authorName: 'Innovation & Incubation Cell',
    createdAt: new Date(Date.now() - 86400000 * 2).toISOString(),
  },
  {
    id: 'not_03',
    title: 'ACM Guest Lecture: Scalable Distributed Systems at Global Cloud Scale',
    content: 'Distinguished lecture on modern distributed consensus algorithms (Raft, Paxos) and low-latency storage engines. Auditorium Hall 4, Thursday at 02:00 PM.',
    category: 'Academic',
    authorName: 'Department of Computer Science',
    createdAt: new Date(Date.now() - 86400000 * 3).toISOString(),
  },
  {
    id: 'not_04',
    title: 'Campus Central Library Extended 24x7 Reading Room Hours',
    content: 'The Central Digital Library will remain open 24x7 through the examination period. High-speed Wi-Fi, reference archives, and discussion rooms will be fully operational.',
    category: 'General',
    authorName: 'Chief University Librarian',
    createdAt: new Date(Date.now() - 86400000 * 5).toISOString(),
  },
];

export const mockTimetable: TimetableEntry[] = [
  {
    id: 'tt_01',
    course: 'B.Tech CSE',
    semester: 'Semester 6',
    subject: 'Data Structures & Algorithms',
    faculty: 'Dr. Sunita Rao',
    day: 'Monday',
    startTime: '09:00 AM',
    endTime: '10:30 AM',
    room: 'Lecture Hall 201',
  },
  {
    id: 'tt_02',
    course: 'B.Tech CSE',
    semester: 'Semester 6',
    subject: 'Cloud Computing & DevOps',
    faculty: 'Prof. Amit Kulkarni',
    day: 'Monday',
    startTime: '10:45 AM',
    endTime: '12:15 PM',
    room: 'Systems Lab 3',
  },
  {
    id: 'tt_03',
    course: 'B.Tech CSE',
    semester: 'Semester 6',
    subject: 'Artificial Intelligence & Neural Nets',
    faculty: 'Dr. Vikram Sen',
    day: 'Monday',
    startTime: '01:30 PM',
    endTime: '03:00 PM',
    room: 'Seminar Hall B',
  },
  {
    id: 'tt_04',
    course: 'B.Tech CSE',
    semester: 'Semester 6',
    subject: 'Database Management Systems',
    faculty: 'Prof. Meera Nair',
    day: 'Tuesday',
    startTime: '09:00 AM',
    endTime: '10:30 AM',
    room: 'Room 304',
  },
  {
    id: 'tt_05',
    course: 'B.Tech CSE',
    semester: 'Semester 6',
    subject: 'Software Engineering & Agile',
    faculty: 'Dr. Rajesh Verma',
    day: 'Tuesday',
    startTime: '11:00 AM',
    endTime: '12:30 PM',
    room: 'Lecture Hall 102',
  },
  {
    id: 'tt_06',
    course: 'B.Tech CSE',
    semester: 'Semester 6',
    subject: 'Cloud Computing Lab Evaluation',
    faculty: 'Prof. Amit Kulkarni',
    day: 'Wednesday',
    startTime: '09:00 AM',
    endTime: '12:00 PM',
    room: 'Cloud Computing Center',
  },
  {
    id: 'tt_07',
    course: 'B.Tech CSE',
    semester: 'Semester 6',
    subject: 'Artificial Intelligence Lab',
    faculty: 'Dr. Vikram Sen',
    day: 'Thursday',
    startTime: '01:30 PM',
    endTime: '04:30 PM',
    room: 'Deep Learning Center',
  },
  {
    id: 'tt_08',
    course: 'B.Tech CSE',
    semester: 'Semester 6',
    subject: 'Open Elective / Industry Seminar',
    faculty: 'Guest Industry Speaker',
    day: 'Friday',
    startTime: '10:00 AM',
    endTime: '12:00 PM',
    room: 'Auditorium Hall 1',
  },
];

export const mockAdminStats: AdminStats = {
  totalStudents: 1420,
  averageAttendance: 78.4,
  activeTasks: 580,
  totalNotices: 12,
  attendanceDistribution: [
    { range: '90-100%', count: 480, percentage: 33.8 },
    { range: '75-89%', count: 640, percentage: 45.1 },
    { range: '65-74%', count: 210, percentage: 14.8 },
    { range: '<65%', count: 90, percentage: 6.3 },
  ],
  weeklyActivity: [
    { day: 'Mon', classes: 24, attendanceRate: 84.5 },
    { day: 'Tue', classes: 22, attendanceRate: 81.2 },
    { day: 'Wed', classes: 26, attendanceRate: 86.8 },
    { day: 'Thu', classes: 20, attendanceRate: 77.4 },
    { day: 'Fri', classes: 25, attendanceRate: 79.1 },
    { day: 'Sat', classes: 12, attendanceRate: 72.0 },
  ],
};

export const mockStudentList: StudentListItem[] = [
  {
    id: 'std_01',
    name: 'Aarav Sharma',
    email: 'student@campus.edu',
    enrollmentNumber: '21BCSE104',
    course: 'B.Tech Computer Science',
    semester: 'Semester 6',
    department: 'School of Computing',
    overallAttendance: 84.8,
    pendingTasks: 3,
    status: 'ACTIVE',
  },
  {
    id: 'std_02',
    name: 'Priya Patel',
    email: 'priya.patel@campus.edu',
    enrollmentNumber: '21BCSE108',
    course: 'B.Tech Computer Science',
    semester: 'Semester 6',
    department: 'School of Computing',
    overallAttendance: 92.1,
    pendingTasks: 1,
    status: 'ACTIVE',
  },
  {
    id: 'std_03',
    name: 'Rohan Mehta',
    email: 'rohan.mehta@campus.edu',
    enrollmentNumber: '21BCSE112',
    course: 'B.Tech Information Tech',
    semester: 'Semester 6',
    department: 'School of Computing',
    overallAttendance: 67.5,
    pendingTasks: 4,
    status: 'ACTIVE',
  },
  {
    id: 'std_04',
    name: 'Sneha Reddy',
    email: 'sneha.reddy@campus.edu',
    enrollmentNumber: '21BCSE115',
    course: 'B.Tech Computer Science',
    semester: 'Semester 6',
    department: 'School of Computing',
    overallAttendance: 88.0,
    pendingTasks: 2,
    status: 'ACTIVE',
  },
];
